[package]
name = "proxy-filter-cli"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.42", features = ["derive"] }
proxy-processor = { path = "../proxy-processor" }
reqwest = { version = "0.12.22", features = ["blocking"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
